# docker-compose.yml

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py loaddata ingredients_formatted.json &&
             python manage.py collectstatic --noinput &&
             cp -r /app/collected_static/. /backend_static/static/ &&
             gunicorn --bind 0.0.0.0:8000 backend.wsgi"

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    build: ./nginx/
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/app/media
      - ./docs:/docs
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
